# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 944bbab99534ea1ea156d07e898e3100d18ebda6fa2810b85461b92ef118f1e03c41e5397ec7490227b985e48f6f92b103fdc14fe5375a0d6114ea9c3e95ad23

test:
  secret_key_base: 7429c393a1c19c55491d47e2fb59dc3d7336ffa012772a000a306fd51a7a79ff7af6b4d99b95e8046fb0aaa9d16a2cc251ca552ee0fe0753bc0c4281a672724b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
